
import { Inter } from "next/font/google";
import Nav from "./components/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dhananjay Chitale Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-[#FFFBEC] ${inter.className} antialiased`}
      
      >
        <Nav></Nav>
     {children}
      </body>
    </html>
  );
}
