
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Nav from "./components/Nav";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

const mediaSans = localFont({
  src: "../public/fonts/mediasans.otf",
  variable: "--font-mediasans",
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${mediaSans.variable}`}>
      <body
        className={` bg-[#FFFBEC] ${inter.className} antialiased`}
      
      >
        <Nav></Nav>
     {children}
        <Analytics />
      </body>
    </html>
  );
}
